Shaun delete giffy
hungnguyen3/Giffy pull request #15
Opened 2023-01-04 00:08 UTC by sbshaun

After selecting/unselecting a Giffy, 
- it will be added/removed to 'selectedGiffies' in Redux store

and after pressing the delete button, 
- it can be deleted from the database

### can't be deleted from Redux store somehow, I have to refresh to see the deletion. 

### TODO: delete from Firebase.

2023-01-05 02:10 UTC, sbshaun commented
### Trying to add a file reference to Firebase when uploading a giffy, since it's needed when deleting a file. 

See: [Firebase-Storage-Deleete-Files](https://firebase.google.com/docs/storage/web/delete-files)

2023-01-06 04:33 UTC, hungnguyen3 reviewed
good so far. Fix all the change requests and the PR is good to go

2023-01-06 04:33 UTC, hungnguyen3 commented on webapp/components/Auth.tsx
> +
remove unused imports

2023-01-06 04:33 UTC, hungnguyen3 commented on webapp/components/DeleteGiffyConfirmationWindow.tsx
> +	const selectedGiffies = useAppSelector(
group all the hooks(useXYZ) together and put this line `const { collectionId } = router.query;` on top

2023-01-06 04:33 UTC, hungnguyen3 commented on webapp/components/DeleteGiffyConfirmationWindow.tsx
> +						});
remove the selected first before closing the window

2023-01-06 04:33 UTC, hungnguyen3 commented on webapp/components/DeleteGiffyConfirmationWindow.tsx
> +															// not working
working

2023-01-06 04:33 UTC, hungnguyen3 commented on webapp/components/DeleteGiffyConfirmationWindow.tsx
> +						selectedGiffies.map(async (giffyId: number) => {
instead of map try to use forEach

2023-01-06 04:33 UTC, hungnguyen3 commented on webapp/components/DeleteGiffyConfirmationWindow.tsx
> +								}
handle else case here

2023-01-06 04:33 UTC, hungnguyen3 commented on webapp/components/DeleteGiffyConfirmationWindow.tsx
> +										.filter((giffy: giffyDTO) => {
`.filter((giffy: giffyDTO) => giffy.giffyId === giffyId)`

2023-01-06 04:33 UTC, hungnguyen3 commented on webapp/components/DeleteGiffyConfirmationWindow.tsx
> +											const giffyStorageRef = ref(storage, giffy.firebaseRef);
no need for this line

2023-01-06 04:33 UTC, hungnguyen3 commented on webapp/components/Header.tsx
>  	const dropdownBlockRef = useRef<HTMLInputElement | null>(null);
clean up and organize these

2023-01-06 04:33 UTC, hungnguyen3 commented on webapp/slices/CollectionsSlice.ts
> +import { collectionDTO, giffyDTO } from '../API/DTO';
remove collectionDTO

2023-01-06 04:33 UTC, hungnguyen3 commented on webapp/slices/CollectionsSlice.ts
> +			}
if (index !== -1) state.selectedGiffyIds.splice(index, 1);

2023-01-06 04:33 UTC, hungnguyen3 commented on webapp/slices/CollectionsSlice.ts
> +		},
delete this reducer. Not used

2023-01-06 04:33 UTC, hungnguyen3 commented on webapp/styles/Card.module.scss
>  .card {
put card into cardsList

2023-01-06 04:33 UTC, hungnguyen3 commented on webapp/styles/Card.module.scss
>  .titleWhite {
delete titleWhite and titleBlack

2023-01-06 04:34 UTC, hungnguyen3 requested changes
change the stuff please

2023-01-08 08:24 UTC, hungnguyen3 approved these changes
good work

2023-01-08 08:24 UTC, merged