Adding users to collection
hungnguyen3/Giffy pull request #21
Opened 2023-02-08 10:44 UTC by mtuntang

finish implementing https://github.com/hungnguyen3/Giffy/issues/17
close https://github.com/hungnguyen3/Giffy/issues/17

Able to make  add users to a collection request (BE only, no FE) with Postman

Notes:
-  Should define what 'write' permission can do such as changing visibility of collection or just adding/deleting giffies

2023-02-28 09:19 UTC, sbshaun commented
can add a user to a collection by email, 
can't change the permission after being added, 
should be able to change or delete a user's permission.

2023-03-01 07:38 UTC, hungnguyen3 requested changes

2023-03-01 07:38 UTC, hungnguyen3 commented on server/routes/collection-user-relationships.ts
> +router.post('/addCollectionUserRelationship', addCollectionUserRelationship);
you need to protect these two new endpoints with the authentication and permission middleware, take a look at src/middleware folder

2023-03-01 07:38 UTC, hungnguyen3 commented on server/routes/route-helpers/collection-user-relationships-helpers.ts
> +export const addCollectionUserRelationship = async (
you should just send the email of the user to the backend. Use the email to query the id instead of sending the ID from the frontend.

2023-03-01 07:38 UTC, hungnguyen3 commented on server/routes/route-helpers/users-helpers.ts
> +export const getUserByEmail = async (req: any, res: any) => {
You should not have this function here. This is a big security risk! No one should be able to look up a user's information by having their email.

2023-03-01 07:38 UTC, hungnguyen3 commented on server/routes/users.ts
> +router.get(
same as above. It's a big security risk. We can have this endpoint. But the information returned should be limited. like we shouldn't include userId, userFirebaseAuthId, or any sensitive information.

2023-03-01 07:38 UTC, hungnguyen3 commented on server/routes/route-helpers/users-helpers.ts
> +export const getUserByEmail = async (req: any, res: any) => {
We can have this endpoint. However, the information returned should be limited. like we shouldn't include userId, userFirebaseAuthId, or any sensitive information. Best to remove in my opinion.

2023-03-01 07:38 UTC, hungnguyen3 commented on webapp/API/collectionUserRelationshipsHooks.ts
> +				credentials: 'same-origin',
use credentials: 'include' here

2023-03-01 07:38 UTC, hungnguyen3 commented on webapp/API/collectionUserRelationshipsHooks.ts
> +				credentials: 'same-origin',
same here, credentials: 'include'

2023-03-01 07:38 UTC, hungnguyen3 commented on webapp/components/CollectionPermissionBox.tsx
> +		if (!['read', 'write', 'admin'].includes(newPermission)) {
you can probably make use of UserPermission type here

2023-04-28 06:50 UTC, merged