Users/hnguyen/5/basic api endpoints
hungnguyen3/Giffy pull request #6
Opened 2022-04-04 01:41 UTC by chiashenglin0204

Issue #5 : Finish user CRUD endpoints

2022-04-04 02:08 UTC, hungnguyen3 requested changes

2022-04-04 02:08 UTC, hungnguyen3 commented on server/routes/route-helpers.ts/users-helpers.ts
> +    .then(() => res.send("you have successfully created a user"))
change this to `res.status(200).send("you have successfully created a user")`.

to have a status code for whether it is successful or not. 200 is a standard code for success.

2022-04-04 02:08 UTC, hungnguyen3 commented on server/routes/route-helpers.ts/users-helpers.ts
> +    .then(() => res.send("you have successfully created a user"))
[check out this link](https://www.dotcom-monitor.com/blog/2022/03/03/the-10-most-common-http-status-codes/#:~:text=Status%20Code%20404%20%E2%80%93%20The%20most,due%20to%20improper%20URL%20redirection.)

2022-04-04 02:08 UTC, hungnguyen3 commented on server/routes/route-helpers.ts/users-helpers.ts
> +    .catch((e: any) => res.json({ error: e }));
same here, `res.status(404).json({error: e})`

read more about what 404 error is [here](https://www.dotcom-monitor.com/blog/2022/03/03/the-10-most-common-http-status-codes/#:~:text=Status%20Code%20404%20%E2%80%93%20The%20most,due%20to%20improper%20URL%20redirection.)

also other places also need status codes too. I won't put a comment in all of them.

2022-04-04 02:08 UTC, hungnguyen3 commented on server/routes/route-helpers.ts/users-helpers.ts
> +      res.send("you have successfully deleted a user uid: " + req.params.userId)
status code 200

2022-04-04 05:45 UTC, chiashenglin0204 commented
Please review my changes for status code, I'm not sure the status code for the error with rowCount > 1 but I put 404 for now

2022-04-04 19:16 UTC, hungnguyen3 commented
> Please review my changes for status code, I'm not sure the status code for the error with rowCount > 1 but I put 404 for now

mostly looks good! However, it seems like you misunderstand the status code `400`. We can discord later and I will explain this!

2022-04-05 03:27 UTC, hungnguyen3 approved these changes

2022-04-05 03:27 UTC, merged